# 1. Service Identification
server.port=8081
spring.application.name=auth-service

# 2. Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/agrosamridhi_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=priyesh17
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Force Hibernate to know it's communicating with MySQL 8+ right away
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Eureka Registration
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true