server:
  port: 8084

spring:
  application:
    name: ai-inference-service
  codec:
    max-in-memory-size: 10MB   

eureka:
  client:
  
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

gemini:
  api:
    key: ${GEMINI_API_KEY}    
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
